compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

npmRegistryServer: "https://registry.yarnpkg.com"

pnpEnableEsmLoader: true

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - darwin
    - linux
